version: '3'

services:
  server1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./data.log:/app/data.log
    environment:
      - SERVER_PORT=8081

  server2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    volumes:
      - ./data.log:/app/data.log
    environment:
      - SERVER_PORT=8082

  server3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    volumes:
      - ./data.log:/app/data.log
    environment:
      - SERVER_PORT=8083
